[package]
name = "redoxer"
version = "0.2.9"
description = "Method for quickly running programs inside of Redox from a KVM capable OS."
license = "MIT"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
repository = "https://gitlab.redox-os.org/redox-os/redoxer"
edition = "2018"

[dependencies]
dirs = "1.0"
redox_installer = "0.2"
redox_syscall = "0.1"
redoxfs = "0.3.6"
tempfile = "3.0"
toml = "0.5"

[target.'cfg(target_os = "linux")'.dependencies]
proc-mounts = "0.2"
