[package]
name = "redoxer"
version = "0.1.0"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2018"

[dependencies]
redox_installer = "0.2"
tempfile = "3.0"
toml = "0.5"

[target.'cfg(target_os = "linux")'.dependencies]
proc-mounts = "0.2"
