[package]
name = "redoxer"
version = "0.2.26"
description = "Method for quickly running programs inside of Redox from a KVM capable OS."
license = "MIT"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
repository = "https://gitlab.redox-os.org/redox-os/redoxer"
edition = "2018"

[dependencies]
dirs = "2.0.2"
redox_installer = "0.2.9"
redox_syscall = "0.2.11"
redoxfs = "0.5.0"
tempfile = "3.1.0"
toml = "0.5.6"

[target.'cfg(target_os = "linux")'.dependencies]
proc-mounts = "0.2.4"
