# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
ca-certificates = {}
coreutils = {}
dash = {}
drivers = {}
extrautils = {}
findutils = {}
ipcd = {}
kernel = {}
logd = {}
netdb = {}
netstack = {}
netutils = {}
nulld = {}
ptyd = {}
randd = {}
redoxerd = {}
uutils = {}
zerod = {}

# User settings
[users.root]
password = ""
uid = 0
gid = 0
name = "root"
home = "/root"

[[files]]
path = "/etc/init.d/00_base"
data = """
nulld
zerod
randd
ipcd
logd
ptyd
pcid /etc/pcid/filesystem.toml
"""

[[files]]
path = "/etc/init.d/10_net"
data = """
smolnetd
dnsd
dhcpd
"""

[[files]]
path = "/etc/init.d/20_redoxer"
data = """
redoxerd
"""

[[files]]
path = "/etc/net/dns"
data = """
208.67.222.222
"""

[[files]]
path = "/etc/net/ip"
data = """
10.0.2.15
"""

[[files]]
path = "/etc/net/ip_router"
data = """
10.0.2.2
"""

[[files]]
path = "/etc/net/ip_subnet"
data = """
255.255.255.0
"""

[[files]]
path = "/etc/net/mac"
data = """
54-52-00-ab-cd-ef
"""

[[files]]
path = "/etc/group"
data = """
root;0;root
"""

[[files]]
path = "/etc/hostname"
data = """
redox
"""

[[files]]
path = "/usr/bin"
data = "/bin"
symlink = true

[[files]]
path = "/usr/games"
data = "/games"
symlink = true

[[files]]
path = "/usr/include"
data = "/include"
symlink = true

[[files]]
path = "/usr/lib"
data = "/lib"
symlink = true

[[files]]
path = "/usr/share"
data = "/share"
symlink = true

[[files]]
path = "/tmp"
data = ""
directory= true
# 0o1777
mode = 1023
